<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2019r3

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="http://www.yellowtwig.nl/training/xmlxslt" exclude-result-prefixes="xs fn ns0">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_PurchaseOrder" as="node()?" select="ns0:PurchaseOrder"/>
		<Order>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'file:///C:/workspace/xmlxslt/xsd-1/order.xsd'"/>
			<xsl:for-each select="$var1_PurchaseOrder">
				<xsl:attribute name="id" select="xs:string(xs:date(fn:string(ns0:CreatedOn)))"/>
			</xsl:for-each>
			<Inhoud>
				<xsl:for-each select="$var1_PurchaseOrder">
					<aantal>
						<xsl:sequence select="xs:string(xs:integer(fn:string(ns0:insuredValue)))"/>
					</aantal>
				</xsl:for-each>
			</Inhoud>
		</Order>
	</xsl:template>
</xsl:stylesheet>
