<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2019r3

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="http://www.yellowtwig.nl/training/xmlxslt" exclude-result-prefixes="xs fn ns0">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:template match="/">
		<PurchaseOrder xmlns="http://www.yellowtwig.nl/training/xmlxslt">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'http://www.yellowtwig.nl/training/xmlxslt file:///C:/workspace/xmlxslt/xsd-1/PurchaseOrder.xsd'"/>
			<OrderLines>
				<xsl:for-each select="ns0:PurchaseOrder/ns0:OrderLines/ns0:OrderLine">
					<OrderLine>
						<xsl:sequence select="(./@node(), ./node())"/>
					</OrderLine>
				</xsl:for-each>
			</OrderLines>
		</PurchaseOrder>
	</xsl:template>
</xsl:stylesheet>
